[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dopamine-framework"
version = "1.0.0"
description = "Best discord.py framework. Automatically check and sync commands, easy-to-use in-Discord dashboard, logging backend, and more. Made by smite-codes."
readme = "README.md"
dependencies = [
    "discord.py>=2.0.0",
    "aiosqlite",
    "psutil",
    "pillow",
    "geocoder"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dopamine_framework.ext" = ["*.ttf"]